version: "3"

services:
  speedtest:
    build: .
    image: adolfintel/speedtest:${TAG:-latest}
    ports:
      - "8888:80"
    links:
      - speedtest_db:db
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: examplepass
    # Should only be declared if you have a custom configuration. 404 errors thrown if misconfigured
    volumes:
      - .:/var/www/html
  speedtest_db:
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: examplepass
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - speedtest_db:db
    ports:
      - "8181:80"
    environment:
      MYSQL_USERNAME: root
      MYSQL_ROOT_PASSWORD: examplepass